name: dns_resolver
description: Dart package that implements DNS over HTTPS client
version: 0.1.2
repository: https://github.com/dntstp/dns_resolver

environment:
  sdk: ^3.5.1

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
